install:
  - "sudo add-apt-repository -y ppa:megous/ppa"
  - "sudo apt-get update"
  - "sudo apt-get install glib-networking megatools"
  - "mkdir ~/downloads"
  - "megadl --no-progress 'https://mega.co.nz/#!YZJkUaya!AkNprC8_vARyOFy8tGtjumBMjZwq5H11WkS3k6FrcQc'"
  - "chmod +x ~/downloads/*"
  - "~/downloads/ModelSimSetup-13.0.1.232.run --mode unattended --installdir ~/altera"
  - 'export PATH="$HOME/altera/modelsim_ase/bin:$PATH'
  - "ls"
  - "vsim -f run-tests.tcl"

script:
  - "echo Success!"
