install:
  - "sudo apt-get -qq install aptitude"
  - "sudo aptitude -q2 update && sudo aptitude -q2 -y install ia32-libs"
  - "mkdir ~/downloads"
  - "wget -O ~/downloads/modelsim.run https://dl.dropboxusercontent.com/u/6090385/ModelSimSetup-13.0.1.232.run"
  - "chmod +x ~/downloads/modelsim.run"
  - "~/downloads/modelsim.run --mode unattended --installdir ~/altera"
  - 'export PATH="$HOME/altera/modelsim_ase/bin:$PATH"'

script:
  - "utils/make-tests.sh"
